machine:
  pre:
  # https://discuss.circleci.com/t/docker-1-10-0-is-available-beta/2100
  - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
  services:
    - docker
dependencies:
  pre:
    # 安裝 eb
    - pip install --upgrade pip
    - sudo apt-get install -y python-dev
    - pip install awsebcli
    - sudo pip install docker-compose==1.8.0
test:
  override:
    - ./node_modules/.bin/mocha
    # 使用 curl 測試 docker 是否有順利執行 node
    - docker-compose up -d
    - curl --retry 10 --retry-delay 5 -v http://localhost:3000
deployment:
  production:
    branch: master
    commands:
      # - eb deploy env-production